# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/triage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/triage.proto\"U\n\x0ePatientProfile\x12\x0c\n\x04\x63nic\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12\x0b\n\x03lat\x18\x04 \x01(\x01\x12\x0b\n\x03lng\x18\x05 \x01(\x01\"\x89\x02\n\x0bLeanPayload\x12\x0f\n\x07\x63\x61se_id\x18\x01 \x01(\t\x12 \n\x07patient\x18\x02 \x01(\x0b\x32\x0f.PatientProfile\x12\x17\n\x0f\x63hief_complaint\x18\x03 \x01(\t\x12\x10\n\x08symptoms\x18\x04 \x03(\t\x12\x10\n\x08severity\x18\x05 \x01(\x05\x12\x14\n\x0ctriage_level\x18\x06 \x01(\t\x12\x15\n\rtriage_reason\x18\x07 \x01(\t\x12\x1c\n\x14\x63onversation_summary\x18\x08 \x01(\t\x12\x16\n\x0etimestamp_unix\x18\t \x01(\x03\x12\x11\n\tdevice_id\x18\n \x01(\t\x12\x14\n\x0cnetwork_mode\x18\x0b \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.triage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PATIENTPROFILE._serialized_start=22
  _PATIENTPROFILE._serialized_end=107
  _LEANPAYLOAD._serialized_start=110
  _LEANPAYLOAD._serialized_end=375
# @@protoc_insertion_point(module_scope)
