// Local RAG engine — searches the bundled WHO knowledge base using pure-JS
// cosine similarity against Float32 embeddings generated by all-MiniLM-L6-v2.
//
// Index priority (highest first):
//   1. documentDirectory/knowledge_meta.json + knowledge_embeddings.json
//      (downloaded from server by KnowledgeBaseUpdateService — may be newer)
//   2. apps/mobile/src/assets/knowledge/ (baseline bundled at install time)
//
// Silent failure everywhere: if neither source exists, query() returns [].

import {
  documentDirectory,
  getInfoAsync,
  readAsStringAsync,
} from 'expo-file-system/legacy';

// ── Public types ───────────────────────────────────────────────────────────────

export interface ChunkMetadata {
  content: string;
  articleTitle: string | null;
  articleUrl: string | null;
  articleAuthor: string | null;
  articleSource: string | null;
}

export interface RAGResult {
  content: string;
  articleTitle: string | null;
  articleSource: string | null;
  score: number;
}

// ── Internal types ─────────────────────────────────────────────────────────────

// Shape of knowledge_embeddings.json written by the seed script.
// `data` is a base64-encoded flat Float32Array (row-major, 384 floats per chunk).
interface EmbeddingsFile {
  data: string;
  dims: number;
  count: number;
}

// ── Constants ──────────────────────────────────────────────────────────────────

const SIMILARITY_THRESHOLD = 0.6;
const DIMS = 384; // all-MiniLM-L6-v2 output dimension

// ── Service ────────────────────────────────────────────────────────────────────

class LocalRAGService {
  private embeddings: Float32Array | null = null;
  private metadata: ChunkMetadata[] = [];
  private isLoaded = false;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  private embeddingPipeline: any = null;

  /**
   * Load the index files. Tries documentDirectory first, then bundled assets.
   * Must be called once at app startup (called by App.tsx after DB init).
   * Silent failure — sets isLoaded = false if no index is found.
   */
  async initialize(): Promise<void> {
    try {
      const loaded =
        (await this._loadFromDocumentDirectory()) ||
        (await this._loadFromBundledAssets());

      if (!loaded) {
        console.warn('[RAG] No knowledge index found — queries will return empty.');
        return;
      }

      this.isLoaded = true;
      console.log(`[RAG] Ready — ${this.metadata.length} chunks loaded.`);
    } catch (err) {
      console.warn('[RAG] Initialization failed silently:', err);
    }
  }

  /**
   * Search the index for chunks relevant to `symptomText`.
   * Returns up to `topK` results with score >= 0.6, sorted descending.
   * Returns [] if the index has not been loaded or the query embedding fails.
   */
  async query(symptomText: string, topK = 3): Promise<RAGResult[]> {
    if (!this.isLoaded || !this.embeddings || this.metadata.length === 0) {
      return [];
    }

    try {
      const queryVec = await this._embed(symptomText);
      const scores   = this._computeAllSimilarities(queryVec);

      return scores
        .map((score, i) => ({ score, i }))
        .filter(({ score }) => score >= SIMILARITY_THRESHOLD)
        .sort((a, b) => b.score - a.score)
        .slice(0, topK)
        .map(({ score, i }) => ({
          content:       this.metadata[i]!.content,
          articleTitle:  this.metadata[i]!.articleTitle,
          articleSource: this.metadata[i]!.articleSource,
          score:         Math.round(score * 10000) / 10000,
        }));
    } catch (err) {
      console.warn('[RAG] Query failed silently:', err);
      return [];
    }
  }

  // ── Loading ──────────────────────────────────────────────────────────────────

  private async _loadFromDocumentDirectory(): Promise<boolean> {
    try {
      const metaPath = `${documentDirectory}knowledge_meta.json`;
      const embPath  = `${documentDirectory}knowledge_embeddings.json`;

      const [metaInfo, embInfo] = await Promise.all([
        getInfoAsync(metaPath),
        getInfoAsync(embPath),
      ]);

      if (!metaInfo.exists || !embInfo.exists) return false;

      const [metaStr, embStr] = await Promise.all([
        readAsStringAsync(metaPath),
        readAsStringAsync(embPath),
      ]);

      this._applyIndex(
        JSON.parse(metaStr) as ChunkMetadata[],
        JSON.parse(embStr) as EmbeddingsFile,
      );
      console.log('[RAG] Loaded updated index from documentDirectory.');
      return true;
    } catch {
      return false;
    }
  }

  private async _loadFromBundledAssets(): Promise<boolean> {
    try {
      // Metro resolves JSON requires at bundle time — no runtime IO needed.
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const meta: ChunkMetadata[] = require('../../assets/knowledge/knowledge_meta.json');
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const emb: EmbeddingsFile   = require('../../assets/knowledge/knowledge_embeddings.json');
      this._applyIndex(meta, emb);
      console.log('[RAG] Loaded baseline index from bundled assets.');
      return true;
    } catch {
      return false;
    }
  }

  private _applyIndex(meta: ChunkMetadata[], emb: EmbeddingsFile): void {
    this.metadata   = meta;
    this.embeddings = this._base64ToFloat32(emb.data);
  }

  // ── Embedding ────────────────────────────────────────────────────────────────

  private async _embed(text: string): Promise<Float32Array> {
    if (!this.embeddingPipeline) {
      // Lazy-init: model is cached after first call
      const { pipeline } = await import('@xenova/transformers');
      this.embeddingPipeline = await pipeline(
        'feature-extraction',
        'Xenova/all-MiniLM-L6-v2',
        { quantized: true },
      );
    }
    const out = await (this.embeddingPipeline as (
      text: string,
      opts: Record<string, unknown>,
    ) => Promise<{ data: Float32Array }>)(text, { pooling: 'mean', normalize: true });
    return out.data;
  }

  // ── Math ─────────────────────────────────────────────────────────────────────

  private _computeAllSimilarities(query: Float32Array): number[] {
    const n      = this.metadata.length;
    const emb    = this.embeddings!;
    const qNorm  = this._l2Norm(query);
    const scores = new Array<number>(n);

    for (let i = 0; i < n; i++) {
      const off = i * DIMS;
      let dot   = 0;
      let eNorm = 0;
      for (let d = 0; d < DIMS; d++) {
        const e = emb[off + d]!;
        dot   += query[d]! * e;
        eNorm += e * e;
      }
      // Embeddings from the seed script are already L2-normalised,
      // so eNorm ≈ 1.0; the guard avoids division by zero.
      scores[i] = dot / (qNorm * Math.sqrt(eNorm) + 1e-10);
    }

    return scores;
  }

  private _l2Norm(v: Float32Array): number {
    let s = 0;
    for (let i = 0; i < v.length; i++) s += v[i]! * v[i]!;
    return Math.sqrt(s);
  }

  private _base64ToFloat32(b64: string): Float32Array {
    const binary = atob(b64);
    const bytes  = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return new Float32Array(bytes.buffer);
  }
}

// ── Exports ───────────────────────────────────────────────────────────────────

export const localRAG = new LocalRAGService();

/** Named export — backward-compatible with SymptomCollectorAgent. */
export async function queryKnowledgeBase(
  symptomText: string,
  topK = 3,
): Promise<RAGResult[]> {
  return localRAG.query(symptomText, topK);
}
