"use client";

import { useEffect, useState } from "react";
import { CalendarDays, ChevronDown, ChevronUp, Phone, User } from "lucide-react";
import { getAppointments } from "@/lib/api";
import type { AppointmentDetailResponse } from "@/lib/api";

const SPECIALTY_LABELS: Record<string, string> = {
  GENERAL_PHYSICIAN: "General Physician",
  CARDIOLOGIST: "Cardiologist",
  DERMATOLOGIST: "Dermatologist",
  ORTHOPEDIC: "Orthopedic",
  PEDIATRICIAN: "Pediatrician",
  PULMONOLOGIST: "Pulmonologist",
  NEUROLOGIST: "Neurologist",
  OTHER: "Other",
};

const STATUS_STYLES: Record<string, string> = {
  PENDING:   "bg-amber-900/40 text-amber-300 border border-amber-700",
  CONFIRMED: "bg-green-900/40 text-green-300 border border-green-700",
  CANCELLED: "bg-gray-800 text-gray-400 border border-gray-700",
};

const TRIAGE_STYLES: Record<string, string> = {
  GREEN: "bg-green-900/40 text-green-300",
  AMBER: "bg-amber-900/40 text-amber-300",
  RED:   "bg-red-900/40 text-red-300",
};

function formatDateTime(date: string, time: string) {
  return `${date}  ${time}`;
}

function SoapPanel({ soap }: { soap: AppointmentDetailResponse["soap_report"] }) {
  if (!soap) return null;
  return (
    <div className="mt-4 space-y-3 border-t border-gray-700 pt-4">
      <p className="text-xs font-semibold uppercase tracking-wider text-gray-400">
        Pre-Appointment SOAP Note
      </p>
      {(["subjective", "objective", "assessment", "plan"] as const).map((section) => (
        <div key={section}>
          <p className="text-xs font-semibold uppercase tracking-wider text-gray-500 mb-1">
            {section}
          </p>
          <p className="text-sm text-gray-300 leading-relaxed">{soap[section]}</p>
        </div>
      ))}
      <p className="text-xs text-gray-600 pt-1">
        Generated by {soap.model_used} · {new Date(soap.generated_at).toLocaleString()}
      </p>
    </div>
  );
}

function AppointmentCard({ appt }: { appt: AppointmentDetailResponse }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="rounded-xl border border-gray-800 bg-gray-900 overflow-hidden">
      {/* Header row */}
      <div className="flex items-start justify-between p-4 gap-4">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap mb-1">
            <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${TRIAGE_STYLES[appt.triage_level] ?? "bg-gray-800 text-gray-400"}`}>
              {appt.triage_level}
            </span>
            <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${STATUS_STYLES[appt.status] ?? ""}`}>
              {appt.status}
            </span>
          </div>

          <p className="text-sm font-semibold text-white truncate">{appt.chief_complaint}</p>

          <div className="mt-1 flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-gray-400">
            <span className="flex items-center gap-1">
              <User size={11} /> {appt.patient_name}
            </span>
            <span className="flex items-center gap-1">
              <Phone size={11} /> {appt.patient_phone}
            </span>
            <span className="flex items-center gap-1">
              <CalendarDays size={11} />
              {formatDateTime(appt.slot_date, appt.slot_time)}
            </span>
          </div>

          <p className="mt-1 text-xs text-gray-500">
            {appt.practitioner_name} · {SPECIALTY_LABELS[appt.practitioner_specialty] ?? appt.practitioner_specialty} · {appt.clinic_name}, {appt.city}
          </p>
        </div>

        {appt.soap_report && (
          <button
            onClick={() => setExpanded((v) => !v)}
            className="shrink-0 flex items-center gap-1 rounded-lg border border-gray-700 px-3 py-1.5 text-xs text-gray-300 hover:bg-gray-800 transition"
          >
            SOAP {expanded ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
          </button>
        )}
      </div>

      {/* Expandable SOAP panel */}
      {expanded && (
        <div className="border-t border-gray-800 px-4 pb-4">
          <SoapPanel soap={appt.soap_report} />
        </div>
      )}

      {!appt.soap_report && appt.triage_level !== "GREEN" && (
        <div className="border-t border-gray-800 px-4 py-2">
          <p className="text-xs text-gray-600 italic">SOAP note generating…</p>
        </div>
      )}
    </div>
  );
}

export default function AppointmentsPage() {
  const [appointments, setAppointments] = useState<AppointmentDetailResponse[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getAppointments()
      .then((res) => setAppointments(res.appointments))
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  const pending   = appointments.filter((a) => a.status === "PENDING");
  const confirmed = appointments.filter((a) => a.status === "CONFIRMED");
  const other     = appointments.filter((a) => a.status !== "PENDING" && a.status !== "CONFIRMED");

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-xl font-bold text-white">Appointments</h1>
        <p className="mt-1 text-sm text-gray-400">
          Incoming patient bookings for your practitioners. Expand any card to view the pre-attached SOAP note.
        </p>
      </div>

      {loading ? (
        <div className="space-y-3">
          {Array.from({ length: 3 }).map((_, i) => (
            <div key={i} className="h-24 animate-pulse rounded-xl border border-gray-800 bg-gray-900" />
          ))}
        </div>
      ) : appointments.length === 0 ? (
        <div className="flex flex-col items-center justify-center rounded-xl border border-gray-800 bg-gray-900 py-20 text-center">
          <CalendarDays size={36} className="mb-3 text-gray-600" />
          <p className="text-sm text-gray-500">No appointments yet</p>
          <p className="mt-1 text-xs text-gray-600">
            Patients will appear here once they book through the mobile app.
          </p>
        </div>
      ) : (
        <div className="space-y-6">
          {pending.length > 0 && (
            <section>
              <h2 className="mb-3 text-xs font-semibold uppercase tracking-wider text-amber-400">
                Pending ({pending.length})
              </h2>
              <div className="space-y-3">
                {pending.map((a) => <AppointmentCard key={a.id} appt={a} />)}
              </div>
            </section>
          )}

          {confirmed.length > 0 && (
            <section>
              <h2 className="mb-3 text-xs font-semibold uppercase tracking-wider text-green-400">
                Confirmed ({confirmed.length})
              </h2>
              <div className="space-y-3">
                {confirmed.map((a) => <AppointmentCard key={a.id} appt={a} />)}
              </div>
            </section>
          )}

          {other.length > 0 && (
            <section>
              <h2 className="mb-3 text-xs font-semibold uppercase tracking-wider text-gray-500">
                Other ({other.length})
              </h2>
              <div className="space-y-3">
                {other.map((a) => <AppointmentCard key={a.id} appt={a} />)}
              </div>
            </section>
          )}
        </div>
      )}
    </div>
  );
}
