"use client";

import { useEffect, useState } from "react";
import { X, MapPin } from "lucide-react";
import { format } from "date-fns";
import { getCaseById } from "@/lib/api";
import type { CaseDetail } from "@/lib/api";
import { TriageBadge } from "./TriageBadge";

interface Props {
  caseId: string | null;
  onClose: () => void;
}

const soapSections = [
  { key: "subjective" as const, label: "S — Subjective", border: "border-l-blue-500" },
  { key: "objective" as const, label: "O — Objective", border: "border-l-purple-500" },
  { key: "assessment" as const, label: "A — Assessment", border: "border-l-amber-500" },
  { key: "plan" as const, label: "P — Plan", border: "border-l-green-500" },
];

function SkeletonLine({ className = "" }: { className?: string }) {
  return <div className={`h-4 animate-pulse rounded bg-gray-700 ${className}`} />;
}

export function SoapReportPanel({ caseId, onClose }: Props) {
  const [caseDetail, setCaseDetail] = useState<CaseDetail | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!caseId) return;
    setLoading(true);
    getCaseById(caseId)
      .then(setCaseDetail)
      .catch(() => setCaseDetail(null))
      .finally(() => setLoading(false));
  }, [caseId]);

  if (!caseId) return null;

  return (
    <>
      {/* Backdrop */}
      <div className="fixed inset-0 z-40 bg-black/40" onClick={onClose} />

      {/* Panel */}
      <div className="fixed right-0 top-0 z-50 flex h-full w-[480px] flex-col border-l border-gray-800 bg-gray-900 shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-gray-800 px-6 py-4">
          <h2 className="text-base font-semibold text-white">SOAP Report</h2>
          <button
            onClick={onClose}
            className="rounded-lg p-1.5 text-gray-400 transition-colors hover:bg-gray-800 hover:text-white"
          >
            <X size={18} />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto px-6 py-4">
          {loading ? (
            <div className="space-y-4">
              <SkeletonLine className="w-1/3" />
              <SkeletonLine className="w-2/3" />
              <SkeletonLine />
              <SkeletonLine className="w-3/4" />
            </div>
          ) : !caseDetail ? (
            <p className="text-sm text-gray-500">Failed to load case detail.</p>
          ) : (
            <div className="space-y-5">
              {/* Patient row */}
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-white">
                    {caseDetail.patient_name ?? "Name withheld"}
                  </p>
                  <p className="text-xs text-gray-400">{caseDetail.patient_phone ?? ""}</p>
                </div>
                <TriageBadge level={caseDetail.triage_level} />
              </div>

              {/* Location row */}
              <div className="flex items-center gap-1.5 text-xs text-gray-500">
                <MapPin size={12} />
                <span>
                  {caseDetail.lat.toFixed(6)}, {caseDetail.lng.toFixed(6)}
                </span>
              </div>

              {/* Received time */}
              <p className="text-xs text-gray-500">
                Received {format(new Date(caseDetail.received_at), "PPpp")}
              </p>

              {/* SOAP sections */}
              {caseDetail.soap_report ? (
                soapSections.map(({ key, label, border }) => (
                  <div
                    key={key}
                    className={`rounded-lg border-l-4 bg-gray-800 p-4 ${border}`}
                  >
                    <p className="mb-2 text-xs font-bold uppercase tracking-wider text-gray-400">
                      {label}
                    </p>
                    <p className="text-sm leading-relaxed text-gray-300">
                      {caseDetail.soap_report![key]}
                    </p>
                  </div>
                ))
              ) : (
                <div className="rounded-lg border border-dashed border-gray-700 p-6 text-center">
                  <p className="text-sm text-gray-500">SOAP report not yet available.</p>
                  <p className="mt-1 text-xs text-gray-600">
                    {caseDetail.triage_level === "GREEN"
                      ? "GREEN cases do not generate SOAP reports."
                      : "The report is being generated — check back in a moment."}
                  </p>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Footer */}
        {caseDetail?.soap_report && (
          <div className="border-t border-gray-800 px-6 py-3">
            <p className="text-xs text-gray-500">
              Generated by {caseDetail.soap_report.model_used} ·{" "}
              {format(new Date(caseDetail.soap_report.generated_at), "PPp")}
            </p>
          </div>
        )}
      </div>
    </>
  );
}
